name: ticket_widget
description: Ui package to make a beautiful ticket like animated widget
version: 1.0.0
homepage: https://github.com/DholaSain/Ticket-Widget

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: